apiVersion: v1
kind: Service
metadata:
  name: video-api-v1
spec:
  type: NodePort
  ports:
  - name: kjsp
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: video-api-v1

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: video-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-api-v1
  template:
    metadata:
      labels:
        app: video-api-v1
    spec:
      containers:
      - name: video-api-v1-pod
        image: alfierichou/video-api-v1:0.0.1
        ports:
        - containerPort: 4000